import Calculator from '@/components/Apps/Calculator';
import Notes from '@/components/Apps/Notes';
import PhotoBooth from '@/components/Apps/PhotoBooth';
import Safari from '@/components/Apps/Safari';
import SnakeGame from '@/components/Apps/SnakeGame';
import Terminal from '@/components/Apps/Terminal';
import { INITIAL_INDEX } from '@/constants/app';
import { LinkApp, WindowApp } from '@/types/app';

export const apps: (WindowApp | LinkApp)[] = [
  {
    id: 'notes',
    title: 'Notes',
    imageUrl: 'src/assets/icons/Dock/Notes_Icon.png',
    initialX: 300,
    initialY: 100,
    minWidth: 800,
    minHeight: 600,
    zIndex: INITIAL_INDEX,
    isOpen: false,
    isMinimize: false,
    isResizable: true,
    content: <Notes />,
    type: 'window',
  },
  {
    id: 'safari',
    title: 'Safari',
    imageUrl: 'src/assets/icons/Dock/Safari_Icon.png',
    initialX: 600,
    initialY: 300,
    minWidth: 1000,
    minHeight: 650,
    zIndex: INITIAL_INDEX,
    isOpen: false,
    isMinimize: false,
    isResizable: true,
    content: <Safari />,
    type: 'window',
  },
  {
    id: 'photo_booth',
    title: 'Photo Booth',
    imageUrl: 'src/assets/icons/Dock/Photo_Booth_Icon.png',
    initialX: 700,
    initialY: 400,
    minWidth: 600,
    minHeight: 500,
    zIndex: INITIAL_INDEX,
    isOpen: false,
    isMinimize: false,
    isResizable: false,
    content: <PhotoBooth />,
    type: 'window',
  },
  {
    id: 'calculator',
    title: 'Calculator',
    imageUrl: 'src/assets/icons/Dock/Calculator_Icon.png',
    initialX: 700,
    initialY: 200,
    minWidth: 300,
    minHeight: 400,
    zIndex: INITIAL_INDEX,
    isOpen: false,
    isMinimize: false,
    isResizable: false,
    content: <Calculator />,
    type: 'window',
  },
  {
    id: 'terminal',
    title: 'Terminal',
    imageUrl: 'src/assets/icons/Dock/Terminal_Icon.png',
    initialX: 400,
    initialY: 200,
    minWidth: 800,
    minHeight: 600,
    zIndex: INITIAL_INDEX,
    isOpen: false,
    isMinimize: false,
    isResizable: true,
    content: <Terminal />,
    type: 'window',
  },
  {
    id: 'github',
    title: 'Github',
    imageUrl: 'src/assets/icons/Dock/Github_Icon.png',
    link: 'https://github.com/shaw-kee/shawkee-os',
    type: 'link',
  },
  {
    id: 'snake_game',
    title: 'Snake Game',
    imageUrl: 'src/assets/icons/Dock/Terminal_Icon.png',
    initialX: 300,
    initialY: 400,
    minWidth: 400,
    minHeight: 400,
    zIndex: INITIAL_INDEX,
    isOpen: false,
    isMinimize: false,
    isResizable: false,
    content: <SnakeGame />,
    type: 'window',
  },
];
